string  genicam_module   # Name of the module
string  genicam_node     # Name of the GenICam node
int64   value         # integer value of the enumeration entry
---
stcamera_msgs/ErrorInfo error_info # Error information
