string  genicam_module   # Name of the module
string  genicam_node     # Name of the GenICam node
string  value         # Symbolic name of the enumeration entry
---
stcamera_msgs/ErrorInfo error_info # Error information
