string  genicam_module   # Name of the module
string  genicam_node     # Name of the GenICam node
int64	address		 # start address
int64	length		 # length of the data to write
uint8[]  data             # data
---
stcamera_msgs/ErrorInfo error_info # Error information
